package com.mtl.qcvmt.migration;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.sql.DataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(1)
@ConditionalOnProperty(prefix = "qcvmt.migration", name = "enabled", havingValue = "true")
public class OracleToMysqlMigrationRunner implements CommandLineRunner {

  private static final Logger log = LoggerFactory.getLogger(OracleToMysqlMigrationRunner.class);
  private static final DateTimeFormatter DATETIME_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  private final DataSource mysqlDataSource;
  private final MigrationProperties properties;

  public OracleToMysqlMigrationRunner(
      @Qualifier("mysqlDataSource") DataSource mysqlDataSource,
      MigrationProperties properties) {
    this.mysqlDataSource = mysqlDataSource;
    this.properties = properties;
  }

  @Override
  public void run(String... args) throws Exception {
    log.info("[migration] Oracle migration started, mode={}", properties.mode().name());

    if (properties.mode() == MigrationMode.EXPORT_SQL) {
      exportSqlFile();
      return;
    }

    directDbMigrate();
  }

  private void directDbMigrate() throws Exception {
    log.info("[migration] Oracle -> MySQL direct migration started");

    try (Connection oracle = DriverManager.getConnection(
        properties.oracleUrl(), properties.oracleUsername(), properties.oraclePassword());
        Connection mysql = mysqlDataSource.getConnection()) {

      mysql.setAutoCommit(false);
      if (properties.truncateBeforeLoad()) {
        truncateTargets(mysql);
      }

      for (TablePlan plan : plans()) {
        migrateTable(oracle, mysql, plan, properties.batchSize());
      }

      mysql.commit();
      log.info("[migration] Oracle -> MySQL direct migration completed successfully");
    } catch (Exception ex) {
      log.error("[migration] failed", ex);
      throw ex;
    }
  }

  private void exportSqlFile() throws Exception {
    Path output = Paths.get(properties.exportFile());
    Path parent = output.getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }

    try (Connection oracle = DriverManager.getConnection(
        properties.oracleUrl(), properties.oracleUsername(), properties.oraclePassword());
        BufferedWriter writer = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {

      writer.write("-- Generated by OracleToMysqlMigrationRunner");
      writer.newLine();
      writer.write("SET NAMES utf8mb4;");
      writer.newLine();
      writer.write("SET FOREIGN_KEY_CHECKS=0;");
      writer.newLine();
      writer.newLine();

      if (properties.truncateBeforeLoad()) {
        for (String table : reverseOrderTables()) {
          writer.write("TRUNCATE TABLE " + table + ";");
          writer.newLine();
        }
        writer.newLine();
      }

      for (TablePlan plan : plans()) {
        exportTableAsInsertSql(oracle, writer, plan);
      }

      writer.newLine();
      writer.write("SET FOREIGN_KEY_CHECKS=1;");
      writer.newLine();
      writer.flush();
    } catch (Exception ex) {
      log.error("[migration] export sql failed", ex);
      throw ex;
    }

    log.info("[migration] export sql completed: {}", output.toAbsolutePath());
  }

  private List<String> reverseOrderTables() {
    return List.of(
        "t_operation_log",
        "t_showlog",
        "t_cell_matrix",
        "t_vessel_refuel",
        "t_vessel_col",
        "t_col_set",
        "t_vessel",
        "t_user");
  }

  private void truncateTargets(Connection mysql) throws SQLException {
    for (String table : reverseOrderTables()) {
      try (PreparedStatement ps = mysql.prepareStatement("TRUNCATE TABLE " + table)) {
        ps.execute();
        log.info("[migration] truncated {}", table);
      }
    }
  }

  private void migrateTable(Connection oracle, Connection mysql, TablePlan plan, int batchSize)
      throws SQLException {
    String sourceTable = resolveSourceTable(oracle, plan.sourceTableCandidates())
        .orElseThrow(() -> new IllegalStateException(
            "No source table found for target " + plan.targetTable() + ", candidates=" + plan.sourceTableCandidates()));

    List<String> sourceColumns = loadSourceColumns(oracle, sourceTable);
    List<String> selectExpressions = new ArrayList<>();

    for (String targetColumn : plan.targetColumns()) {
      List<String> candidates = plan.sourceColumnCandidates().get(targetColumn);
      if (candidates == null || candidates.isEmpty()) {
        throw new IllegalStateException("No source candidates configured: " + plan.targetTable() + "." + targetColumn);
      }
      selectExpressions.add(resolveSelectExpression(targetColumn, candidates, sourceColumns));
    }

    String selectSql = "SELECT " + String.join(", ", selectExpressions) + " FROM " + sourceTable;
    String insertSql = "INSERT IGNORE INTO " + plan.targetTable() + " ("
        + plan.targetColumns().stream().map(this::mysqlQuote).collect(Collectors.joining(","))
        + ") VALUES ("
        + plan.targetColumns().stream().map(c -> "?").collect(Collectors.joining(","))
        + ")";

    int migrated = 0;
    try (PreparedStatement readPs = oracle.prepareStatement(selectSql);
        ResultSet rs = readPs.executeQuery();
        PreparedStatement writePs = mysql.prepareStatement(insertSql)) {

      while (rs.next()) {
        for (int i = 0; i < plan.targetColumns().size(); i++) {
          writePs.setObject(i + 1, rs.getObject(i + 1));
        }
        writePs.addBatch();
        migrated++;

        if (migrated % batchSize == 0) {
          writePs.executeBatch();
          writePs.clearBatch();
        }
      }

      writePs.executeBatch();
      writePs.clearBatch();
    }

    log.info("[migration] {} <= {} : {} rows", plan.targetTable(), sourceTable, migrated);
  }

  private void exportTableAsInsertSql(Connection oracle, BufferedWriter writer, TablePlan plan)
      throws SQLException, IOException {
    String sourceTable = resolveSourceTable(oracle, plan.sourceTableCandidates())
        .orElseThrow(() -> new IllegalStateException(
            "No source table found for target " + plan.targetTable() + ", candidates=" + plan.sourceTableCandidates()));

    List<String> sourceColumns = loadSourceColumns(oracle, sourceTable);
    List<String> selectExpressions = new ArrayList<>();

    for (String targetColumn : plan.targetColumns()) {
      List<String> candidates = plan.sourceColumnCandidates().get(targetColumn);
      if (candidates == null || candidates.isEmpty()) {
        throw new IllegalStateException("No source candidates configured: " + plan.targetTable() + "." + targetColumn);
      }
      selectExpressions.add(resolveSelectExpression(targetColumn, candidates, sourceColumns));
    }

    String selectSql = "SELECT " + String.join(", ", selectExpressions) + " FROM " + sourceTable;
    String insertPrefix = "INSERT IGNORE INTO " + plan.targetTable() + " ("
        + plan.targetColumns().stream().map(this::mysqlQuote).collect(Collectors.joining(","))
        + ") VALUES (";

    int exported = 0;
    try (PreparedStatement readPs = oracle.prepareStatement(selectSql);
        ResultSet rs = readPs.executeQuery()) {
      while (rs.next()) {
        StringBuilder sql = new StringBuilder(insertPrefix);
        for (int i = 0; i < plan.targetColumns().size(); i++) {
          if (i > 0) {
            sql.append(',');
          }
          sql.append(toMysqlLiteral(rs.getObject(i + 1)));
        }
        sql.append(");");
        writer.write(sql.toString());
        writer.newLine();
        exported++;
      }
      writer.newLine();
    }

    log.info("[migration-export] {} <= {} : {} rows", plan.targetTable(), sourceTable, exported);
  }

  private String toMysqlLiteral(Object value) {
    if (value == null) {
      return "NULL";
    }
    if (value instanceof Number || value instanceof Boolean) {
      return value.toString();
    }
    if (value instanceof Timestamp ts) {
      return "'" + DATETIME_FORMAT.format(ts.toLocalDateTime()) + "'";
    }
    if (value instanceof Date d) {
      return "'" + d.toLocalDate().toString() + "'";
    }
    if (value instanceof Time t) {
      return "'" + t.toLocalTime().toString() + "'";
    }
    if (value instanceof LocalDateTime dt) {
      return "'" + DATETIME_FORMAT.format(dt) + "'";
    }

    String text = value.toString().replace("\\", "\\\\").replace("'", "''");
    return "'" + text + "'";
  }

  private String mysqlQuote(String identifier) {
    return "`" + identifier + "`";
  }

  private Optional<String> resolveSourceTable(Connection oracle, List<String> candidates) {
    for (String candidate : candidates) {
      String sql = "SELECT 1 FROM " + candidate + " WHERE 1 = 0";
      try (PreparedStatement ps = oracle.prepareStatement(sql)) {
        ps.executeQuery();
        return Optional.of(candidate);
      } catch (SQLException ignored) {
      }
    }
    return Optional.empty();
  }

  private List<String> loadSourceColumns(Connection oracle, String table) throws SQLException {
    String sql = "SELECT * FROM " + table + " WHERE 1 = 0";
    try (PreparedStatement ps = oracle.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()) {
      ResultSetMetaData md = rs.getMetaData();
      List<String> columns = new ArrayList<>();
      for (int i = 1; i <= md.getColumnCount(); i++) {
        columns.add(md.getColumnLabel(i));
      }
      return columns;
    }
  }

  private String resolveSelectExpression(String targetColumn, List<String> candidates, List<String> sourceColumns) {
    Map<String, String> normalizedMap = new HashMap<>();
    for (String sourceColumn : sourceColumns) {
      normalizedMap.put(normalize(sourceColumn), sourceColumn);
    }

    for (String candidate : candidates) {
      if (candidate.startsWith("LITERAL:")) {
        String value = candidate.substring("LITERAL:".length());
        return value;
      }
      String matched = normalizedMap.get(normalize(candidate));
      if (matched != null) {
        return matched;
      }
    }

    throw new IllegalStateException("Cannot map target column " + targetColumn + " from candidates " + candidates
        + ", available source columns=" + sourceColumns);
  }

  private String normalize(String text) {
    return text.replace("_", "").replace("-", "").toLowerCase(Locale.ROOT);
  }

  private List<TablePlan> plans() {
    List<TablePlan> plans = new ArrayList<>();

    plans.add(new TablePlan(
        "t_user",
        List.of("id", "keycloak_id", "qcid", "name", "role", "parent", "createtime"),
        List.of("T_USER", "t_user"),
        Map.of(
            "id", List.of("USERID", "ID"),
            "keycloak_id", List.of("LITERAL:NULL"),
            "qcid", List.of("QCID", "qcid"),
            "name", List.of("NAME", "USERNAME"),
            "role", List.of("ROLE"),
            "parent", List.of("PARENT"),
            "createtime", List.of("CREATETIME", "CREATE_TIME"))));

    plans.add(new TablePlan(
        "t_vessel",
        List.of("id", "vesselid", "deck_hold", "bay", "row_start", "row_end", "tier_start", "tier_end", "version"),
        List.of("T_VESSEL", "t_vessel"),
        Map.of(
            "id", List.of("VMID", "ID"),
            "vesselid", List.of("VESSELID"),
            "deck_hold", List.of("DECK_HOLD", "QDECK"),
            "bay", List.of("BAY"),
            "row_start", List.of("ROWSTART", "ROW_START"),
            "row_end", List.of("ROWEND", "ROW_END"),
            "tier_start", List.of("TIERSTART", "TIER_START"),
            "tier_end", List.of("TIEREND", "TIER_END"),
            "version", List.of("VERSION", "LITERAL:0"))));

    plans.add(new TablePlan(
        "t_col_set",
        List.of("id", "boxcase", "color", "version"),
        List.of("T_COL_SET", "T_COLSET", "t_col_set", "t_colset"),
        Map.of(
            "id", List.of("CSID", "COLSETID", "ID", "LITERAL:NULL"),
            "boxcase", List.of("BOXCASE"),
            "color", List.of("COLOR"),
            "version", List.of("VERSION", "LITERAL:0"))));

    plans.add(new TablePlan(
        "t_vessel_col",
        List.of("id", "vesselid", "deck_hold", "bay", "row_start", "row_end", "tier_start", "tier_end", "version"),
        List.of("T_VESSEL_COL", "T_VESSELCOL", "t_vessel_col", "t_vesselcol"),
        Map.of(
            "id", List.of("VCID", "VESSELCOLID", "ID", "LITERAL:NULL"),
            "vesselid", List.of("VESSELID"),
            "deck_hold", List.of("DECK_HOLD", "QDECK"),
            "bay", List.of("BAY"),
            "row_start", List.of("ROWSTART", "ROW_START"),
            "row_end", List.of("ROWEND", "ROW_END"),
            "tier_start", List.of("TIERSTART", "TIER_START"),
            "tier_end", List.of("TIEREND", "TIER_END"),
            "version", List.of("VERSION", "LITERAL:0"))));

    plans.add(new TablePlan(
        "t_vessel_refuel",
        List.of("id", "vesselid", "is_refuel", "version"),
        List.of("T_VESSEL_REFUEL", "T_VESSELREFUEL", "t_vessel_refuel", "t_vesselrefuel"),
        Map.of(
            "id", List.of("VRID", "VESSELREFUELID", "ID", "LITERAL:NULL"),
            "vesselid", List.of("VESSELID"),
            "is_refuel", List.of("IS_REFUEL", "ISREFUEL"),
            "version", List.of("VERSION", "LITERAL:0"))));

    plans.add(new TablePlan(
        "t_cell_matrix",
        List.of("id", "type", "row", "tier", "tier_start", "tier_end", "active"),
        List.of("T_CELL_MATRIX", "T_CELLMATRIX", "t_cell_matrix", "t_cellmatrix"),
        Map.of(
            "id", List.of("CMID", "CELLMATRIXID", "MATRIXID", "ID", "LITERAL:NULL"),
            "type", List.of("TYPE", "CMTYPE"),
            "row", List.of("ROW", "ROW_NO", "CMROW"),
            "tier", List.of("TIER", "CMTIER"),
            "tier_start", List.of("TIERSTART", "TIER_START", "CMTIER", "LITERAL:NULL"),
            "tier_end", List.of("TIEREND", "TIER_END", "CMTIER", "LITERAL:NULL"),
            "active", List.of("ACTIVE", "LITERAL:'1'"))));

    plans.add(new TablePlan(
        "t_showlog",
        List.of("id", "userid", "username", "qcid", "login_time", "operation"),
        List.of("T_SHOWLOG", "t_showlog"),
        Map.of(
            "id", List.of("LOGID", "SHOWLOGID", "ID", "LITERAL:NULL"),
            "userid", List.of("USERID"),
            "username", List.of("USERNAME", "NAME"),
            "qcid", List.of("QCID"),
            "login_time", List.of("LOGIN_TIME", "LOGINTIME"),
            "operation", List.of("OPERATION", "ACTION_TYPE", "LITERAL:'LOGIN'"))));

    plans.add(new TablePlan(
        "t_operation_log",
        List.of("id", "userid", "username", "function_name", "action_type", "old_values", "new_values", "timestamp"),
        List.of("T_OPERATION_LOG", "T_OPERATIONLOG", "t_operation_log", "t_operationlog"),
        Map.of(
            "id", List.of("OPID", "OPERATIONLOGID", "OPERLOGID", "ID", "LITERAL:NULL"),
            "userid", List.of("USERID"),
            "username", List.of("USERNAME", "NAME"),
            "function_name", List.of("FUNCTION_NAME", "FUNCTIONNAME", "FUNCTION"),
            "action_type", List.of("ACTION_TYPE", "ACTIONTYPE"),
            "old_values", List.of("OLD_VALUES", "OLDVALUES", "OLD_VALUE", "VALUECHANGE", "LITERAL:NULL"),
            "new_values", List.of("NEW_VALUES", "NEWVALUES", "NEW_VALUE", "VALUECHANGE", "LITERAL:NULL"),
            "timestamp", List.of("TIMESTAMP", "CREATETIME", "CREATE_TIME", "TIME"))));

    return plans;
  }

  private record TablePlan(
      String targetTable,
      List<String> targetColumns,
      List<String> sourceTableCandidates,
      Map<String, List<String>> sourceColumnCandidates) {
  }

  @Component
  static class MigrationProperties {

    private final org.springframework.core.env.Environment env;

    MigrationProperties(org.springframework.core.env.Environment env) {
      this.env = env;
    }

    String oracleUrl() {
      return required("qcvmt.migration.oracle.url");
    }

    String oracleUsername() {
      return required("qcvmt.migration.oracle.username");
    }

    String oraclePassword() {
      return required("qcvmt.migration.oracle.password");
    }

    boolean truncateBeforeLoad() {
      return Boolean.parseBoolean(env.getProperty("qcvmt.migration.truncate-before-load", "true"));
    }

    int batchSize() {
      return Integer.parseInt(env.getProperty("qcvmt.migration.batch-size", "500"));
    }

    MigrationMode mode() {
      String raw = env.getProperty("qcvmt.migration.mode", "EXPORT_SQL");
      return MigrationMode.valueOf(raw.trim().toUpperCase(Locale.ROOT));
    }

    String exportFile() {
      return env.getProperty("qcvmt.migration.export-file", "build/migration/oracle_to_mysql_insert.sql");
    }

    private String required(String key) {
      String value = env.getProperty(key);
      if (value == null || value.isBlank()) {
        throw new IllegalStateException("Missing required property: " + key);
      }
      return value;
    }
  }

  enum MigrationMode {
    DIRECT_DB,
    EXPORT_SQL
  }
}
