hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.show_sql=true

database.driver=oracle.jdbc.driver.OracleDriver

#DEV
#database.url=jdbc:oracle:thin:@//172.23.1.5:1661/mqcvmtdev.hkg.corp.modernterminals.com
#database.user=mqcvmt
#database.password=mqcvmtdev

#SIT
database.url=jdbc:oracle:thin:@//172.23.2.5:1661/mqcvmtsit.hkg.corp.modernterminals.com
database.user=mqcvmtapp
database.password=mqcvmtappsit

#UAT
#database.url=jdbc:oracle:thin:@//172.23.3.6:1661/mqcvmtuat.hkg.corp.modernterminals.com
#database.user=mqcvmtapp
#database.password=mqcvmtappuat

#Prod
#database.url=jdbc:oracle:thin:@(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS=(PROTOCOL=TCP)(HOST=m1n4dbl19p02)(PORT=1661))(CONNECT_DATA=(SERVICE_NAME=mqcvmt.HKG.CORP.MODERNTERMINALS.COM)))(DESCRIPTION=(CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS=(PROTOCOL=TCP)(HOST=m1n4dbl19p11)(PORT=1661))(CONNECT_DATA=(SERVICE_NAME=mqcvmt.HKG.CORP.MODERNTERMINALS.COM))))
#database.user=mqcvmtapp
#database.password=cervix33

# connection pool setting
vmt.c3p0.maxIdleTime = 60
vmt.c3p0.min_size = 10
vmt.c3p0.max_size = 40
vmt.c3p0.initialPoolSize = 10
vmt.c3p0.checkoutTimeout=10000
vmt.c3p0.unreturnedConnectionTimeout=10

n4.c3p0.maxIdleTime = 60
n4.c3p0.min_size = 10
n4.c3p0.max_size = 50
n4.c3p0.initialPoolSize = 10

# purge executeTime format : Second Minute Hour Date Month WeekDay (Year)
N4.dataExchange.executeTime=0 0/5 * * * ?