log4j.rootCategory=INFO, stdout , R
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d-[QCVMT] %p %t %c - %m%n
log4j.appender.R=org.apache.log4j.DailyRollingFileAppender
log4j.appender.R.File=/app/qcvmt/apache-tomcat-9.0.98/logs/qcvmt.log
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d-[QCVMT] %p %t %c - %m%n
log4j.logger.qcvmt=INFO
log4j.logger.org.springframework=INFO