#get all qc numbers from company DCB1 International
company=T9' , 'T125

#set the cookie age for two weeks
cookieMaxAge=1209600

#set the continued time when the LOAD case finished. and need refer the refresh time
loadTimeCount=4

#set import vessel upload folder /home/qcvmt/tomcat7/webapps/MQCVMT/upload
uploadFolder=/app/qcvmt/upload


limitAccount=abc